

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mlmd-
spec:
  entrypoint: wf
  templates:
  - name: wf
    steps:
    - - name: importer
        template: importer
    - - name: multiplier
        template: multiplier
    - - name: print
        template: print
        when: "{{steps.multiplier.outputs.parameters.multiplier-output}} > 1.5"
        arguments:
          parameters:
          - name: multiplier-output-accuracy
            value: "{{steps.multiplier.outputs.parameters.multiplier-output}}"
  - name: importer
    container:
      image: gcr.io/yang-experiment-6/mlmd:0.6
      command: ["python3"]
      args:
        - -u
        - /kfp/launcher/importer.py
        - --outputs_json
        # change accuracy to 1 will trigger the condition
        - '{"outputs":{"artifacts":[{"key":"pipeline_input", "value":{"custom_properties":[{"key":"accuracy","value":1}]}}]}}'
        - --argo_workflow_name
        - "{{workflow.name}}"
        - --pod_name
        - "{{pod.name}}"
  - name: multiplier
    container:
      image: gcr.io/yang-experiment-6/mlmd:0.6
      command: ["python3"]
      args:
        - -u
        - /kfp/launcher/launcher.py
        - --inputs_json
        - '{"inputs":{"artifacts":[{"key":"pipeline_input", "value":{"producer_task":"importer", "output_artifact_key":"pipeline_input"}}]}}'
        - --outputs_json
        - '{"outputs":{"artifacts":[{"key":"multiplier-output", "value":{"custom_properties":[{"key":"accuracy"}]}}]}}'
        - --argo_workflow_name
        - "{{workflow.name}}"
        - --pod_name
        - "{{pod.name}}"
    outputs:
      parameters:
      - name: multiplier-output
        valueFrom:
          path: /tmp/outputs/artifacts/multiplier-output/custom_properties/accuracy
  - name: print
    inputs:
      parameters:
      - name: multiplier-output-accuracy
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.multiplier-output-accuracy}}"]