apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mlmd-
spec:
  entrypoint: wf
  templates:
  - name: wf
    steps:
    - - name: importer
        template: importer
    - - name: multiplier
        template: multiplier
    - - name: print
        template: print
        when: "{{steps.multiplier.outputs.parameters.artifacts_multiplier-output_custom_properties_accuracy}} > 1.5"
        arguments:
          parameters:
          - name: multiplier-output-accuracy
            value: "{{steps.multiplier.outputs.parameters.artifacts_multiplier-output_custom_properties_accuracy}}"
  - name: importer
    container:
      image: gcr.io/yang-experiment-6/mlmd:0.2
      command: ["python3"]
      args:
        - -u
        - /kfp/launcher/importer.py
        - --inputs_json
        - '{"inputs":{"artifacts":[{"key":"pipeline_input", "value":{"custom_properties":[{"key":"accuracy","value":0}]}}]}}'
        - --argo_workflow_name
        - "{{workflow.name}}"
        - --pod_name
        - "{{pod.name}}"
  - name: multiplier
    container:
      image: gcr.io/yang-experiment-6/mlmd:0.2
      command: ["python3"]
      args:
        - -u
        - /kfp/launcher/launcher.py
        - --inputs_json
        - '{"inputs":{"artifacts":[{"key":"pipeline_input", "value":{"producer_task":"importer", "output_artifact_key":"pipeline_input"}}]}}'
        - --outputs_json
        - '{"outputs":{"artifacts":[{"key":"multiplier-output", "value":{"custom_properties":[{"key":"accuracy"}]}}]}}'
        - --argo_workflow_name
        - "{{workflow.name}}"
        - --pod_name
        - "{{pod.name}}"
    outputs:
      parameters:
      - name: artifacts_multiplier-output_custom_properties_accuracy
        valueFrom:
          path: /tmp/artifacts_multiplier-output_custom_properties_accuracy
  - name: print
    inputs:
      parameters:
      - name: multiplier-output-accuracy
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.multiplier-output-accuracy}}"]



  inputs: {
    artifacts: {
      key: "examples"
      value: {
        producer_task: "example-gen"
        output_artifact_key: "examples"
      }
    }
  }