apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mlmd-
spec:
  entrypoint: wf
  templates:
  - name: wf
    steps:
    - - name: step-one
        template: step-one
    - - name: print
        template: print
        when: "{{steps.step-one.outputs.parameters.artifacts_step-one-output_custom_properties_accuracy}} > 1.5"
        arguments:
          parameters:
          - name: step-one-output-accuracy
            value: "{{steps.step-one.outputs.parameters.artifacts_step-one-output_custom_properties_accuracy}}"
  - name: step-one
    container:
      image: gcr.io/yang-experiment-6/mlmd:0.2
      command: ["python3"]
      args:
        - -u
        - /kfp/launcher/metadata_writer.py
        - --inputs_json
        - '{"inputs":{"artifacts":[{"key":"step-one-input", "value":{"custom_properties":[{"key":"accuracy","value":0}]}}]}}'
        - --outputs_json
        - '{"outputs":{"artifacts":[{"key":"step-one-output", "value":{"custom_properties":[{"key":"accuracy"}]}}]}}'
        - --argo_workflow_name
        - "{{workflow.name}}"
        - --pod_name
        - "{{pod.name}}"
    outputs:
      parameters:
      - name: artifacts_step-one-output_custom_properties_accuracy
        valueFrom:
          path: /tmp/artifacts_step-one-output_custom_properties_accuracy
  - name: print
    inputs:
      parameters:
      - name: step-one-output-accuracy
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.step-one-output-accuracy}}"]
